blank_issues_enabled: false

contact_links:
  - name: Meediscussiëren
    url: https://github.com/orgs/security-commons-nl/discussions
    about: Vragen, ervaringen of ideeën delen zonder directe actie

  - name: Geen GitHub-account?
    url: https://github.com/signup
    about: Gratis registreren duurt 2 minuten. Of vraag iemand uit je netwerk om namens jou een bericht te plaatsen.
